---
version: 2.1
orbs:
  tfenv: suzuki-shunsuke/tfenv@dev:a03cbf649e03ca5a2b703d5d2ffcf09eb6828768
workflows:
  build:
    jobs:
      - tfenv/setup:
          name: setup

      - tfenv/test:
          name: test foo/staging
          requires:
            - setup
          dir: src/services/foo/staging
          tfnotify_config_path: src/.tfnotify.yaml
          custom_tests:
            - tflint:
                dir: src/services/foo/staging

      - tfenv/test:
          name: test foo/production
          requires:
            - setup
          dir: src/services/foo/production
          tfnotify_config_path: src/.tfnotify.yaml
          custom_tests:
            - tflint:
                dir: src/services/foo/production

      - tfenv/check_changed:
          name: Check changed states
          requires:
            - setup
            - test foo/staging
            - test foo/production
          result_dir: changed
          setup_dir: .ci

      - tfenv/apply:
          name: apply
          requires:
            - setup
            - test foo/staging
            - test foo/production
          filters:
            branches:
              only:
                - master

# Custom test with tflint
commands:
  install_tflint:
    parameters:
      dir:
        type: string
    steps:
      - run:
          name: Install tflint
          shell: /bin/bash -eu -o pipefail
          command: |
            bin_dir=$PWD/<< parameters.dir >>
            mkdir -p $bin_dir
            dirpath=$(mktemp -d)
            cd $dirpath
            curl -LO https://github.com/terraform-linters/tflint/releases/download/v0.15.1/tflint_linux_amd64.zip
            unzip tflint_linux_amd64.zip
            mv tflint $bin_dir/tflint
            chmod a+x $bin_dir/tflint
            rm -R $dirpath
  tflint:
    parameters:
      dir:
        type: string
    steps:
      - install_tflint:
          dir: .ci/bin
      - run:
          name: tflint
          shell: /bin/bash -eu -o pipefail
          command: |
            export PATH=$PWD/.ci/bin:$PATH
            cd << parameters.dir >>
            if ! tflint; then
              echo_error "tflint is failure"
              github-comment -template ":x: [Job Link]($CIRCLE_BUILD_URL) [<< parameters.dir >>] tflint is failure"
              exit 1
            fi
