---
version: 2.1
orbs:
  tfenv: suzuki-shunsuke/tfenv@dev:pr-10
workflows:
  build:
    jobs:
      - tfenv/setup:
          name: setup
          custom_setup:
            - tfenv/install_tflint

      - tfenv/test:
          name: test
          dir: "."
          custom_tests:
            - tfenv/tflint
          requires:
            - setup

      - tfenv/check_changed:
          name: Check changed states
          requires:
            - setup
            - test

      - tfenv/apply:
          name: apply
          requires:
            - setup
            - test
          filters:
            branches:
              only:
                - master
