---
version: 2.1
orbs:
  tfenv: suzuki-shunsuke/tfenv@0.2.0
workflows:
  build:
    jobs:
      - tfenv/setup:
          name: setup

      - tfenv/test:
          name: test
          dir: "."
          requires:
            - setup

      - tfenv/check_changed:
          name: Check changed states
          requires:
            - setup
            - test

      - tfenv/apply:
          name: apply
          requires:
            - setup
            - test
          filters:
            branches:
              only:
                - master
